server:
  port: 8889

#spring:
#  application:
#    name: config-client
#  profiles:
#    active: dev
#  config:
#    import: optional:configserver:http://root:s3cr3t@localhost:8888
#
#user:
#  role: development

spring:
  application:
    name: spring-cloud-client
  datasource:
    username: dbuser
    password: password
